# 🌟 Minimal Starship Theme
# Clean and fast prompt with essential information only

format = """$directory$character"""

#add_newline = false

# Directory
[directory]
style = "blue"
truncation_length = 2
truncate_to_repo = true
format = ""
#format = "[$path]($style) "

# Git branch (very simple)
[git_branch]
symbol = ""
style = "green"
format = "[$branch]($style) "

# Character (simple arrow)
[character]
success_symbol = "[>](fg:#1E1E1E)"
error_symbol = "[>](fg:#D70022)"

# Disable most modules for minimal theme
[package]
disabled = true

[nodejs]
disabled = true

[python]
disabled = true

[rust]
disabled = true

[golang]
disabled = true

[java]
disabled = true

[docker_context]
disabled = true

[kubernetes]
disabled = true

[git_commit]
disabled = true

[git_state]
disabled = true

[git_metrics]
disabled = true

[cmd_duration]
disabled = true

[status]
disabled = true

[time]
disabled = true

[username]
disabled = true

[hostname]
disabled = true

[battery]
disabled = true

[memory_usage]
disabled = true
