[theme]
name = "catppuccin-frappe-yellow"

[colors]
AlertInfo = "#a6d189"
AlertWarn = "#ef9f76"
AlertError = "#e78284"
Annotation = "#e5c890"
Base = "#c6d0f5"
Guidance = "#949cbb"
Important = "#e78284"
Title = "#e5c890"
