[theme]
name = "catppuccin-frappe-sapphire"

[colors]
AlertInfo = "#a6d189"
AlertWarn = "#ef9f76"
AlertError = "#e78284"
Annotation = "#85c1dc"
Base = "#c6d0f5"
Guidance = "#949cbb"
Important = "#e78284"
Title = "#85c1dc"
