[theme]
name = "catppuccin-frappe-green"

[colors]
AlertInfo = "#a6d189"
AlertWarn = "#ef9f76"
AlertError = "#e78284"
Annotation = "#a6d189"
Base = "#c6d0f5"
Guidance = "#949cbb"
Important = "#e78284"
Title = "#a6d189"
