[theme]
name = "catppuccin-frappe-rosewater"

[colors]
AlertInfo = "#a6d189"
AlertWarn = "#ef9f76"
AlertError = "#e78284"
Annotation = "#f2d5cf"
Base = "#c6d0f5"
Guidance = "#949cbb"
Important = "#e78284"
Title = "#f2d5cf"
