[theme]
name = "catppuccin-frappe-pink"

[colors]
AlertInfo = "#a6d189"
AlertWarn = "#ef9f76"
AlertError = "#e78284"
Annotation = "#f4b8e4"
Base = "#c6d0f5"
Guidance = "#949cbb"
Important = "#e78284"
Title = "#f4b8e4"
