# git
brew "git"
# NodeJS
brew "node"
# Display tree output
brew "tree"
# Perl
brew "perl"
# Scala
brew "scala"
# Scala build tool
brew "sbt"
# Fuzzy finder
brew "fzf"
# zoxide, auto jump
brew "zoxide"
# diff-so-fancy, git diff tool
brew "diff-so-fancy"
# JSON parser
brew "jq"
# Python 3
brew "python"
# Java build tool
brew "maven"
# Text editor
brew "vim"
# Improved `cat`
brew "bat"
# Faster `grep
brew "ripgrep"
# More useable `find`
brew "fd"
# Check bash scripts for problems
brew "shellcheck"
# GNU flavored utils
brew "coreutils"
# GitHub Markdown file previewer (dep. of vim plugin "vim-markdown-preview")
brew "grip"
# Find out the wifi password
brew "wifi-password"
# IDEA
cask "pycharm"
# IDEA
cask "intellij-idea"
# Spotlight with workflows
cask "alfred"
# Media streamer
cask "vlc"
# Gaming platform
cask "steam"
# Decompression tool
cask "the-unarchiver"

# Mac App Store apps
mas "AdBlock", id: 1402042596
mas "Xcode", id: 497799835
mas "Monosnap", id: 540348655
mas "iMovie", id: 408981434
mas "Airmail", id: 918858936
mas "Adblock Plus", id: 1432731683
mas "Amphetamine", id: 937984704
