# ⭐ Starship Configuration
# Fast, customizable prompt for any shell

# Enhanced prompt format - FULL FEATURED with all modules
format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$package\
$nodejs\
$python\
$rust\
$golang\
$java\
$docker_context\
$cmd_duration\
$line_break\
$character"""

# Right side modules
right_format = """
$status\
$time"""

# Add a line break before the prompt
add_newline = true

# Username (only show when not default user)
[username]
style_user = "yellow bold"
style_root = "red bold"
format = "[$user]($style) "
disabled = false
show_always = false

# Hostname (only show when in SSH)
[hostname]
ssh_only = true
format = "on [$hostname](bold red) "
disabled = false

# Directory
[directory]
style = "cyan bold"
read_only = " 🔒"
read_only_style = "red"
truncation_length = 3
truncate_to_repo = true
format = "in [$path]($style)[$read_only]($read_only_style) "

# Git branch
[git_branch]
symbol = "🌱 "
style = "bold purple"
format = "on [$symbol$branch]($style) "

# Git commit
[git_commit]
commit_hash_length = 7
style = "bold green"
format = "[\\($hash$tag\\)]($style) "

# Git state (for rebasing, merging, etc.)
[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "[🍒 PICKING](bold red)"
rebase = "[📝 REBASING](bold yellow)"
merge = "[🔀 MERGING](bold yellow)"
revert = "[🔄 REVERTING](bold red)"
bisect = "[🔍 BISECTING](bold yellow)"
am = "[📧 AM](bold blue)"
am_or_rebase = "[📧 AM/REBASE](bold blue)"

# Git metrics (insertions/deletions)
[git_metrics]
added_style = "bold green"
deleted_style = "bold red"
format = '([+$added]($added_style) )([-$deleted]($deleted_style) )'
disabled = false

# Command duration
[cmd_duration]
min_time = 2_000
style = "yellow bold"
format = "took [$duration]($style) "

# Character (prompt symbol)
[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vicmd_symbol = "[❮](bold green)"

# Status (exit code of last command)
[status]
style = "bg:red"
symbol = "💥 "
format = '[\[$symbol$status\]]($style) '
disabled = false

# Time
[time]
disabled = false
style = "bold white"
format = "[$time]($style)"
time_format = "%T"

# Language versions (show when in project)
[nodejs]
symbol = "⬢ "
style = "bold green"
format = "via [$symbol($version )]($style)"

[python]
symbol = "🐍 "
style = "bold yellow"
format = 'via [${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[rust]
symbol = "🦀 "
style = "bold red"
format = "via [$symbol($version )]($style)"

[golang]
symbol = "🐹 "
style = "bold cyan"
format = "via [$symbol($version )]($style)"

[java]
symbol = "☕ "
style = "bold red"
format = "via [$symbol($version )]($style)"

# Package managers
[package]
symbol = "📦 "
style = "208 bold"
format = "is [$symbol$version]($style) "
disabled = false

# Docker
[docker_context]
symbol = "🐳 "
style = "blue bold"
format = "via [$symbol$context]($style) "

# Kubernetes
[kubernetes]
format = 'on [⛵ $context \($namespace\)](dimmed green) '
disabled = false

# Battery
[battery]
full_symbol = "🔋 "
charging_symbol = "⚡️ "
discharging_symbol = "💀 "

[[battery.display]]
threshold = 10
style = "bold red"

[[battery.display]]
threshold = 30
style = "bold yellow"

# Memory usage
[memory_usage]
disabled = false
threshold = 70
symbol = "🐏 "
style = "bold dimmed white"
format = "via $symbol[${ram}( | ${swap})]($style) "

# Shell
[shell]
fish_indicator = "🐠 "
powershell_indicator = "🪟 "
bash_indicator = "💥 "
zsh_indicator = "⚡ "
disabled = true

# Disabled modules
[aws]
disabled = true

[gcloud]
disabled = true

[terraform]
disabled = true

[vagrant]
disabled = true

[nix_shell]
disabled = true

[conda]
disabled = true
