name: CI

on: push

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Lint
      uses: ludeeus/action-shellcheck@master
      with:
        ignore: vim shell zsh  # Ignore vim, shell and zsh dirs
