name: Health Check

on:
  schedule:
    # Run health check daily at 6 AM UTC
    - cron: '0 6 * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  health-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt-get install -y zsh bash git vim shellcheck
        
    - name: Make scripts executable
      run: |
        find scripts -name "*.sh" -exec chmod +x {} \;
        if [[ -d "scripts/bin" ]]; then
          find scripts/bin -type f -exec chmod +x {} \;
        fi
        
    - name: Run comprehensive health check
      run: |
        # Create minimal config environment for testing
        mkdir -p ~/.config/zsh
        
        # Run health check
        ./scripts/health-check.sh --quick
        
    - name: Check for security issues
      run: |
        # Check for potential security issues
        ./scripts/health-check.sh --security || echo "Security check completed with warnings"
        
    - name: Performance baseline
      run: |
        # Check performance metrics
        ./scripts/profile-shell.sh --startup || echo "Performance check completed"
        
    - name: Dependency audit
      run: |
        # Check dependency health
        ./scripts/check-deps.sh --core
        
    - name: Generate health report
      run: |
        # Generate comprehensive health report
        {
          echo "# Dotfiles Health Report"
          echo "Generated: $(date)"
          echo ""
          echo "## Test Results"
          echo ""
          echo "### Configuration Health"
          ./scripts/health-check.sh --config || echo "Configuration issues detected"
          echo ""
          echo "### Security Health"  
          ./scripts/health-check.sh --security || echo "Security issues detected"
          echo ""
          echo "### Performance Health"
          ./scripts/profile-shell.sh --startup || echo "Performance issues detected"
          echo ""
          echo "### Dependencies"
          ./scripts/check-deps.sh --core || echo "Dependency issues detected"
        } > health-report.md
        
    - name: Upload health report
      uses: actions/upload-artifact@v3
      with:
        name: health-report
        path: health-report.md
        retention-days: 30
        
    - name: Comment on latest commit (if issues found)
      if: failure()
      run: |
        echo "Health check failed. Please review the health report artifact."